### ISSUE TITLE
activer le debug log

### ISSUE THREAD

**Issue by u2pitchjami** [tiff75009/ygg-scrappey#1]
Bonjour,
merci pour votre tuto

Malheureusement je ne parviens pas à le rendre fonctionnel (pour l'instant),
j'ai l'impression que squid s'installe et fonctionne correctement (même si je ne maitrise pas l'ensemble des parametres du fichier de conf), je vois des connexions au début refusées puis acceptées.
Par contre j'ai l'impression qu'il ne se passe rien avec le ygg-scrappey, j'ai 0 log dans mon interface scrappey.com
![image](https://github.com/user-attachments/assets/69ba1b69-c296-4625-83d3-df88807af34f)
donc aucune demande n'est réalisée via scrappey

Je vois dans les logs ygg-scrappey un mode log debug désactivé par défaut, comment faire pour l'activer ?
cela pourrait me permettre d'y voir plus clair.
merci d'avance
bonne journée

**Comment by u2pitchjami** [comment]
re, bon je n'ai pas trouvé comment activer les logs debug mais pas grave, j'ai réussi à rendre actif [ygg-scrappey] et donc de lui demander de passer les requêtes via scrappey (je les vois maintenant dans mon interface)
par contre pb de catégories dans prowlarr...

**Comment by tiff75009** [comment]
Toujours un problème ? Pour le problème de catégorie, j'ai déjà eu ça. Pour moi ça venait du cookie.

**Comment by u2pitchjami** [comment]
Bonsoir,
oui effectivement un modifiant le cookie cela fonctionne (étrange car j'ai l'impression d'avoir récupéré le cookie au moins 25 fois depuis hier, mais bon...)
Par contre chose étrange (ou pas),
lorsque j'ai modifié le cookie dans Prowlarr, cela a fonctionné directement alors que je n'avais pas encore mis à jour la variable cookie du docker compose de ygg-scrappey
cette variable n'est pas utilisée ?
merci !!!

**Comment by tiff75009** [comment]
Non la variable n'est pas réellement utilisé, et toute façon le cookie se réactualise seul, pour le reste si un jour ygg ne fonctionne pas pendant plusieurs heures, il pourra pas update le cookie, donc il faudra remettre le cookie toi même dans le main.py, ou relancer le docker avec ton cookie à jour ^^ sinon ça fait plaisir que ça fonctionne pour toi !

**Comment by u2pitchjami** [comment]
oui merci,
par contre ça fonctionne via prowlarr mais pas via radarr ou sonarr
il faudrait les intégrer au proxy ?

**Comment by tiff75009** [comment]
Bah non rien à voir, si ça fonctionne via prowlarr, normalement ton radarr et sonarr fonctionne aussi... ça n'a aucun rapport

radarr utilise juste le tracker prowlarr, si dans prowlarr ton test est valide, dans radarr si tu as bien ajouté l'url et l'api prowlarr ça doit fonctionner

**Comment by u2pitchjami** [comment]
ha ok, étrange alors
je vais tenter une nouvelle installation sur une vm pour voir si cela change quelques choses
merci
